### ISSUE TITLE
License statement

### ISSUE THREAD

**Issue by brody2consult** [EionRobb/phonegap-win8-sqlite#1]
Can you make an explicit license statement?

Of course, Apache 2.0 would be the most compatible with the Cordova and [01org / cordova-win8](https://github.com/01org/cordova-win8) projects.

As I just commented in brodysoft/Cordova-SQLitePlugin#129, I would like to include your `websql.js` script in [brodysoft / Cordova-SQLitePlugin](https://github.com/brodysoft/Cordova-SQLitePlugin), which is available under both MIT and Apache 2.0 licenses. Option for both MIT and Apache 2.0 licenses would be great!

**Comment by EionRobb** [comment]
There ya go :)

**Comment by brody2consult** [comment]
Awesome, thanks @EionRobb!

**Comment by pke** [comment]
Also, since you included and modified it, you are missing the license information about the original https://github.com/doo/SQLite3-WinRT
